### ISSUE TITLE
Widget color field doesn't update value until second selection

### ISSUE THREAD

**Issue by stevengliebe** [churchthemes/church-theme-framework#12]
When using 'color' field type on a widget, the initial selection in the color picker doesn't update hex value. Subsequent selections do update.

Works immediately when removing change throttle from ctfw_init_widget_colorpicker() in admin-widgets.js but then Customizer refresh doesn't happen on change.

https://github.com/churchthemes/church-theme-framework/blob/master/js/admin-widgets.js#L214

Any thoughts, @andywilkerson? I think it'll be perfect if we can work this out.

Reference pull request #11

**Comment by andywilkerson** [comment]
My version is without the 'change throttle' and it seems to show updates in the Customizer right away. 

When I open the picker initially and click a color, the hex value is changing in the text input, but the color preview is not showing the setting. If I drag the color or click a second time on the color area it seems to update both the hex and color preview. It's only the very first click where I'm seeing it not react.

**Comment by stevengliebe** [comment]
Are you sure your version isn't using the change throttle? It was in the pull request at https://github.com/churchthemes/church-theme-framework/pull/11/files#diff-73cf1b3a54a80b874dd3dc6cabdd49fbR17

I saw this discussion about it: https://wordpress.org/support/topic/wp-color-picker-change-event

**Comment by andywilkerson** [comment]
You're correct, I do have it. I'm going to pull the update from the repo and test it. I'm still using the original code.

**Comment by andywilkerson** [comment]
I tried a number of alternatives but nothing solved the issue. No matter what changes I applied, I couldn't get the refresh to happen on Customizer without the first click on the color pallet being ignored.

**Comment by stevengliebe** [comment]
It's a bit strange. I'll give it a look if I ever end up using the color field. Feel free to dig in in the meantime if you want to perfect this part. It's still usable as it is, wouldn't you say? It's natural to make a second click when something doesn't work at first. I would think most users will try a series of colors before deciding on one.

**Comment by andywilkerson** [comment]
It was so subtle at first, I thought I had miss-clicked until you pointed out the issue. I think people will have no trouble. It's very unlikely anyone gets the exact color they want on their first click. Adjusting a color is going to require multiple clicks, it's almost a guarantee.

Seeing as it's a know issue in the Customizer and impacts all instances of the WP color picker it may be solved in the near future.

**Comment by stevengliebe** [comment]
Yeah, I'm happy to let it sit.

Thanks for adding the field.
