### ISSUE TITLE
Change filter for map icon

### ISSUE THREAD

**Issue by chriswallace** [churchthemes/church-theme-framework#4]
Would it be possible to change the [map icon filter](https://github.com/churchthemes/church-theme-framework/blob/master/includes/maps.php#L42) to wrap around the color function like so?

```'icon' => apply_filters( 'ctfw_maps_icon_color_file', ctfw_color_url( 'images/map-icon.png' ) ),```

This will make it easier on us to override the changes made by the ctfw_color_url() function.

Long-term, I would love to see all the customization and color functionality removed from the framework, as we use our own Sass customization functionality.

**Comment by stevengliebe** [comment]
I don't know if you're still using this or working with a fork but I removed the icon requiring use of color schemes in [1.6](https://github.com/churchthemes/church-theme-framework/releases/tag/1.6). You can specify a map icon globally via JavaScript now. Something like...

```js
// Global marker image
var ctfw_map_marker_image = whatever.theme_url + '/images/map-marker.png';
var ctfw_map_marker_image_hidpi = whatever.theme_url + '/images/map-marker@2x.png';
var ctfw_map_marker_image_width = 50; // only necessary when providing HiDPI image
var ctfw_map_marker_image_height = 50;
```

The theme I'm working on now isn't going to use color schemes so I may end up making other changes.
