### ISSUE TITLE
Unable to get widgets to display on the front end

### ISSUE THREAD

**Issue by EvanAgee** [churchthemes/church-theme-framework#7]
Greetings, I've just started using church-theme-framework for a theme I'm working on and I'm having a strange issue.

I've enabled all widgets in my theme using:
![image](https://cloud.githubusercontent.com/assets/1692674/7289343/85eddee2-e923-11e4-81fd-43743ce8896b.png)

And they show up just fine on the backend and I'm able to assign them to sidebars. However, when I load the page on the front end all of the core widgets load fine but none of the CT Wigets are loading.

Could you help me out? Thanks so much for this AMAZING AMAZING framework and plugin!

**Comment by stevengliebe** [comment]
Hi Evan,

You'll need to create a template for each widget in your theme in a widget-templates directory (e.g. widget-templates/widget-events.php). The template is necessary for showing the widget's contents on the site in the way you decide. See the ctfw_widgets function and the widget method in includes/classes/widget.php for how it works.

The documentation for the framework is very thin (in particular with regard to using widgets) so I recommend looking at a how an existing theme is using the framework's features: http://churchthemes.com/themes/

**Comment by stevengliebe** [comment]
BTW, I'd love to see what you make. What I see at http://churchinteractive.co is fantastic.

**Comment by EvanAgee** [comment]
Ahh, that makes sense!! Thanks so much!

I'll definitely share when I'm done. I can't tell you how much I appreciate you taking the time to create this framework and the content plugin. I've been dreaming of building a WordPress-based platform specifically to meet the needs of the church for some time now and I was so excited to see how much you've already done!

**Comment by stevengliebe** [comment]
You're welcome. Good luck with your project!
