### ISSUE TITLE
Feature request: Add support for Livestream

### ISSUE THREAD

**Issue by mikeritter** [churchthemes/church-theme-framework#8]

**Comment by mikeritter** [comment]
We're using livestream. Wondering about the feasibility of adding support. I'm going to try just the embed code  from their site, but wanted to post this out there.

**Comment by stevengliebe** [comment]
Hi Mike,

I had another user ask for this a couple weeks ago and added responsive support to the framework for LiveStream embeds. See this gist for what will be included in the next update of the framework (and our themes).

https://gist.github.com/stevengliebe/40276b05ed782d78631a#file-responsive-embeds-js-L28

You can paste LiveStream's embed code into the Video field for sermon posts and by replacing responsive-embeds.js with the version above, they'll be responsive on your site (assuming you're using a theme that uses this feature of the framework).

If you're wanting to embed LiveStream's iframe code in page or post content, use this plugin: https://wordpress.org/plugins/iframe/

Please let me know if you have any questions.
